export const DEFAULT_SETTINGS = {
  cafe_name: "Fana Cafe & Restaurant",
  tagline: "Where Great Coffee Meets Beautiful Moments in Addis Ababa",
  hero_title: "Where Great Coffee Meets Beautiful Moments",
  hero_subtitle: "A cozy café and restaurant located at Town Square Building, 22 Square (Djibouti Street, Bole, Addis Ababa). Designed for coffee lovers, food enthusiasts, families, and friends.",
  hero_bg_image: "https://images.pexels.com/photos/16563658/pexels-photo-16563658.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=1200",
  phone: "0911 065 022",
  address: "Town Square Building, 22 Square, Djibouti Street, Bole, Addis Ababa, Ethiopia",
  plus_code: "2Q7Q+W2 Addis Ababa",
  lat: "9.0148457",
  lng: "38.7875868",
  google_rating: "3.7",
  google_review_count: "28",
  opening_hours: "Open Daily Until 8:30 PM (Hours may vary during holidays)",
  about_title: "Experience Modern Ethiopian Hospitality at 22 Square",
  about_description: "Ethiopia is recognized as the birthplace of Arabica coffee. Located at Town Square Building in 22 Square, Fana Cafe & Restaurant offers a relaxing atmosphere, open kitchen transparency, specialty fruit punches, authentic Ethiopian meals like Beyaynet, and our famous Fana Macchiato.",
  announcement: "☕ Welcome to Fana Cafe & Restaurant (22 Square, Town Square Building)! Scan your table QR to order.",
  logo_url: "",
  receipt_enabled: "true",
  admin_password: "fana2026",
};

export const DEFAULT_TABLES = Array.from({ length: 10 }, (_, i) => ({
  name: `Table ${i + 1}`,
  sortOrder: i + 1,
}));

export const DEFAULT_CATEGORY_ROUTING: Record<string, "barista" | "kitchen"> = {
  // drinks & juices go to BARISTA
  "hot-drinks": "barista",
  "soft-drinks": "barista",
  juices: "barista",
  "juices-fresh": "barista",
  coffee: "barista",
  "juices-fresh-punches": "barista",
  // everything food-tier goes to KITCHEN (chef)
  "ethiopian-traditional-meals": "kitchen",
  sandwich: "kitchen",
  "snack-and-wrap": "kitchen",
  burger: "kitchen",
  pasta: "kitchen",
  pizza: "kitchen",
  rice: "kitchen",
  salad: "kitchen",
  soup: "kitchen",
  "pastry-and-cakes": "kitchen",
  "sides-meals": "kitchen",
  "main-meal": "kitchen",
};

export const DEFAULT_STAFF = [
  { name: "Samuel (Waiter)", role: "waiter", pin: "1111" },
  { name: "Tigist (Waiter)", role: "waiter", pin: "3333" },
  { name: "Hanna (Cashier)", role: "cashier", pin: "2222" },
  { name: "Tesfaye (Barista)", role: "barista", pin: "4444" },
  { name: "Kumneger (Chef)", role: "kitchen", pin: "5555" },
];

export const DEFAULT_CATEGORIES = [
  { id: 1, name: "All Items", slug: "all", icon: "Utensils", sortOrder: 0 },
  { id: 2, name: "Soup", slug: "soup", icon: "Soup", sortOrder: 1 },
  { id: 3, name: "Burger", slug: "burger", icon: "Beef", sortOrder: 2 },
  { id: 4, name: "Pasta", slug: "pasta", icon: "UtensilsCrossed", sortOrder: 3 },
  { id: 5, name: "Salad", slug: "salad", icon: "Salad", sortOrder: 4 },
  { id: 6, name: "Pizza", slug: "pizza", icon: "Pizza", sortOrder: 5 },
  { id: 7, name: "Rice", slug: "rice", icon: "CookingPot", sortOrder: 6 },
];

/**
 * Default categories the owner marked UNNECESSARY and wants gone
 * ("Ethiopian Traditional" … "Pastry & Cakes"). Kept here so:
 *  - the seed never re-inserts them,
 *  - the legacy-slug migration never re-creates them,
 *  - the one-time production prune knows exactly which rows to delete.
 * The owner can still add any category manually later — nothing blocks that.
 */
export const REMOVED_DEFAULT_CATEGORY_SLUGS = [
  "ethiopian-traditional-meals",
  "sandwich",
  "snack-and-wrap",
  "juices",
  "hot-drinks",
  "soft-drinks",
  "pastry-and-cakes",
];

// Legacy slug → new category slug mapping (migration keeps existing items visible)
export const CATEGORY_SLUG_MAP: Record<string, string> = {
  "signature-coffee": "hot-drinks",
  coffee: "hot-drinks",
  "hot-coffee": "hot-drinks",
  "macchiato-coffee": "hot-drinks",
  "fresh-drinks": "juices",
  "cold-drinks": "juices",
  smoothies: "juices",
  food: "ethiopian-traditional-meals",
  meals: "ethiopian-traditional-meals",
  "ethiopian-meals": "ethiopian-traditional-meals",
  traditional: "ethiopian-traditional-meals",
  "ethiopian-traditional": "ethiopian-traditional-meals",
  snacks: "snack-and-wrap",
  "fast-food": "snack-and-wrap",
  wraps: "snack-and-wrap",
  wrap: "snack-and-wrap",
  pastries: "pastry-and-cakes",
  bakery: "pastry-and-cakes",
  cakes: "pastry-and-cakes",
  desserts: "pastry-and-cakes",
  dessert: "pastry-and-cakes",
  burger: "burger",
  burgers: "burger",
  pizzas: "pizza",
  salads: "salad",
  soups: "soup",
  pasta: "pasta",
  sandwiches: "sandwich",
  "soft-drinks": "soft-drinks",
};

export const DEFAULT_MENU_ITEMS = [
  {
    id: 101,
    name: "The Famous Fana Macchiato",
    category: "hot-drinks",
    price: 120,
    description: "Our world-class signature layered Ethiopian macchiato brewed with rich Arabica espresso and steamed microfoam milk.",
    imageUrl: "https://images.pexels.com/photos/6763235/pexels-photo-6763235.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=480",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Menu Highlight, Popular, House Special",
    prepTime: "5 min",
    badge: "Famous Special",
    sortOrder: 1,
  },
  {
    id: 102,
    name: "Mixed Fruit Juice (Spris)",
    category: "juices",
    price: 180,
    description: "Freshly blended multi-layered puree of ripe local avocado, mango, and papaya with optional lemon squeeze.",
    imageUrl: "https://images.pexels.com/photos/31822992/pexels-photo-31822992.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=480",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Menu Highlight, 100% Fresh, Natural",
    prepTime: "7 min",
    badge: "Customer Highlight",
    sortOrder: 2,
  },
  {
    id: 103,
    name: "Chicken Club Sandwich",
    category: "sandwich",
    price: 320,
    description: "Triple-decker layered roasted chicken breast, crispy beef bacon, melted cheddar, egg, lettuce, tomato, served with French fries.",
    imageUrl: "https://images.pexels.com/photos/18626291/pexels-photo-18626291.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=480",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Menu Highlight, Gourmet, Served with Fries",
    prepTime: "15 min",
    badge: "Top Seller",
    sortOrder: 3,
  },
  {
    id: 104,
    name: "Traditional Ethiopian Beyaynet Platter",
    category: "ethiopian-traditional-meals",
    price: 800,
    description: "Generous traditional fasting platter featuring Shiro, Kik Alicha, Misir Wot, Gomen, Atakilt Wot, and fresh Injera.",
    imageUrl: "https://images.pexels.com/photos/6336989/pexels-photo-6336989.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=480",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Traditional Ethiopian, Fasting Feast, Vegan",
    prepTime: "15-20 min",
    badge: "Traditional Platter",
    sortOrder: 4,
  },
  {
    id: 105,
    name: "Golden French Fries",
    category: "snack-and-wrap",
    price: 150,
    description: "Crispy skin-on golden potatoes lightly salted and served hot with tomato ketchup and house chili mayo dip.",
    imageUrl: "https://images.pexels.com/photos/18626291/pexels-photo-18626291.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=480",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Vegan, Crispy Snack",
    prepTime: "10 min",
    badge: "Side Order",
    sortOrder: 5,
  },
  {
    id: 106,
    name: "Traditional Ethiopian Coffee (Jebena)",
    category: "hot-drinks",
    price: 90,
    description: "Authentic slow-brewed single-origin Arabica coffee served fresh from a traditional clay Jebena pot.",
    imageUrl: "https://images.pexels.com/photos/36794595/pexels-photo-36794595.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=480",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Vegan, Traditional, High Altitude",
    prepTime: "8 min",
    badge: "Authentic",
    sortOrder: 6,
  },
  {
    id: 107,
    name: "Special Fruit Punches",
    category: "juices",
    price: 160,
    description: "Ice-chilled naturally refreshing punch made with seasonal Ethiopian fruits including watermelon, passion fruit, and orange.",
    imageUrl: "https://images.pexels.com/photos/33674448/pexels-photo-33674448.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=480",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Refreshing, Natural",
    prepTime: "5 min",
    badge: "Fresh Punch",
    sortOrder: 7,
  },
  {
    id: 108,
    name: "Ethiopian Spiced Chechebsa",
    category: "ethiopian-traditional-meals",
    price: 240,
    description: "Pan-fried flatbread shredded and coat in herbal spiced butter (Niter Kibbeh) and berbere, served warm with plain yogurt.",
    imageUrl: "https://images.pexels.com/photos/6336989/pexels-photo-6336989.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=480",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Spicy, Breakfast Favorite",
    prepTime: "12 min",
    badge: "Ethiopian Classic",
    sortOrder: 8,
  },
  {
    id: 109,
    name: "Delicious Fresh Cake & Pastries",
    category: "pastry-and-cakes",
    price: 200,
    description: "Moist fresh sponge cake with chocolate or vanilla cream frosting, baked fresh daily.",
    imageUrl: "https://images.pexels.com/photos/33313216/pexels-photo-33313216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=480",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Dessert, Fresh Baked",
    prepTime: "2 min",
    badge: "Sweet Choice",
    sortOrder: 9,
  },
];

export const DEFAULT_REVIEWS = [
  {
    customerName: "Tsegaslassie Teklay",
    rating: 5,
    reviewText: "Fana Cafe offers a delightful experience with its delicious food, refreshing fruit punches, and well-prepared coffee. The café stands out for its attractive views and comfortable, relaxing atmosphere, making it a great spot to unwind, meet friends, or enjoy a peaceful break in the heart of Addis Ababa.",
    reviewDate: "3 months ago",
    isApproved: true,
    isVerified: true,
  },
  {
    customerName: "Bisrat Abraha",
    rating: 4,
    reviewText: "An extremely pricy restaurant with items like Beyaynet at 800 Birr. The place is just okay and once the corridor around it finished and with many nice views...",
    reviewDate: "1 month ago",
    isApproved: true,
    isVerified: true,
  },
  {
    customerName: "Abiy Temesgen",
    rating: 3,
    reviewText: "It's a cosy restaurant, and the food is good but nowadays the service becomes terrible, it took us one hour to get what we ordered. And the most annoying and uncomfortable thing is since they have an open kitchen we can see everything.",
    reviewDate: "3 years ago",
    isApproved: true,
    isVerified: true,
  },
];

export const DEFAULT_GALLERY = [
  {
    title: "The Famous Fana Macchiato",
    category: "Coffee",
    imageUrl: "https://images.pexels.com/photos/6763235/pexels-photo-6763235.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    caption: "Layered local Arabica espresso with silky steamed microfoam.",
    sortOrder: 1,
  },
  {
    title: "Mixed Fruit Juice & Punches",
    category: "Juices",
    imageUrl: "https://images.pexels.com/photos/31822992/pexels-photo-31822992.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    caption: "Fresh avocado, mango, and papaya Spris.",
    sortOrder: 2,
  },
  {
    title: "Chicken Club Sandwich with Fries",
    category: "Meals",
    imageUrl: "https://images.pexels.com/photos/18626291/pexels-photo-18626291.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    caption: "Served hot with crispy golden French fries.",
    sortOrder: 3,
  },
  {
    title: "Open Kitchen & Vibe at Town Square Building",
    category: "Vibe",
    imageUrl: "https://images.pexels.com/photos/16563658/pexels-photo-16563658.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    caption: "Cozy atmosphere located at 22 Square, Addis Ababa.",
    sortOrder: 4,
  },
  {
    title: "Fresh Cakes & Pastries",
    category: "Desserts",
    imageUrl: "https://images.pexels.com/photos/33313216/pexels-photo-33313216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    caption: "Delicious baked daily sweet treats.",
    sortOrder: 5,
  },
];
